apiVersion: v1
kind: Service
metadata:
  name: phishguard-backend
  namespace: phishguard
spec:
  selector:
    app: phishguard-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
